# -*- coding: utf-8 -*-
"""SqlQuery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125XGw2fW1_HTeQ4V5k1nu6AnvO-frdiA
"""

!pip install -U transformers

from transformers import pipeline
pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages =[
    {"role": "user","content":"who are you?"},
]
pipe(messages)

from transformers import AutoTokenizer,AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model =AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages =[
    {"role": "user","content":"who are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_genration_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(**inputs,max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

pip install -q gradio transformers torch black autopep8 reportlab requests

# ==========================================================
# SQL QUERY GENERATOR - HISTORY FIX VERSION
# ==========================================================

!pip install -q gradio transformers torch reportlab requests

import gradio as gr
import re
import urllib.parse
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch

SCHEMA = {
    "users": ["id","name","email","signup_date","age","country","status"],
    "orders": ["id","user_id","product_name","amount","order_date","status"],
    "products": ["id","name","price","category","stock"],
    "transactions": ["id","user_id","amount","date","type"]
}

DANGEROUS_KEYWORDS = ['DROP','DELETE','ALTER','TRUNCATE','INSERT','UPDATE','EXEC','EXECUTE']
DANGEROUS_PATTERNS = [';','--','/','/','xp_','sp_']

def is_safe(text):
    text_upper = text.upper()
    for keyword in DANGEROUS_KEYWORDS:
        if keyword in text_upper:
            return False
    for pattern in DANGEROUS_PATTERNS:
        if pattern in text:
            return False
    return True

def get_table_name(query):
    query = query.lower()
    mapping = {
        "users":["user","customer","account","profile"],
        "orders":["order","purchase","buy"],
        "products":["product","item","goods"],
        "transactions":["transaction","payment","transfer"]
    }
    for table, words in mapping.items():
        for word in words:
            if word in query:
                return table
    return None

def extract_conditions(query):
    query = query.lower()
    conditions = []
    if "last month" in query:
        conditions.append("DATE(signup_date) >= DATE('now','-1 month')")
    if "last week" in query:
        conditions.append("DATE(date) >= DATE('now','-7 days')")
    if "last year" in query:
        conditions.append("DATE(signup_date) >= DATE('now','-1 year')")
    amount_match = re.search(r'(greater than|more than|above)\s+(\d+)', query)
    if amount_match:
        conditions.append(f"amount > {amount_match.group(2)}")
    return conditions

query_history = []

def styled_box(content=""):
    return f"""
    <div style="background:#111827;
                padding:20px;
                border-radius:12px;
                border:1px solid #374151;
                min-height:300px;
                overflow-y:auto;">
        {content}
    </div>
    """

def generate_sql(user_input):

    if not user_input.strip():
        return styled_box("⚠ Please enter a query.")

    if not is_safe(user_input):
        return styled_box("❌ Security Alert: Unsafe SQL detected.")

    table = get_table_name(user_input)
    if not table:
        return styled_box("⚠ Could not detect table.")

    sql = f"SELECT * FROM {table}"
    conditions = extract_conditions(user_input)
    if conditions:
        sql += " WHERE " + " AND ".join(conditions)
    sql += " LIMIT 10;"

    # 🔥 IMPORTANT FIX: Append history
    query_history.append({
        "question": user_input,
        "answer": sql
    })

    # 🔥 Build complete history output
    full_output = ""

    for item in query_history:
        full_output += f"""
        <div style="margin-bottom:25px;">
            <div style="color:#60a5fa;font-weight:bold;">🧑 Question:</div>
            <div style="color:white;margin-bottom:10px;">{item['question']}</div>

            <div style="color:#22c55e;font-weight:bold;">🤖 SQL Generated:</div>
            <pre style="color:#e5e7eb;background:#1f2937;
                        padding:10px;border-radius:8px;">
{item['answer']}
            </pre>
        </div>
        """

    return styled_box(full_output)

def clear_history():
    query_history.clear()
    return styled_box()

# ---------------- SHARE & EXPORT SAME ----------------

def whatsapp_share():
    if not query_history:
        return "No queries available."
    message = "📊 SQL Queries Generated:\n\n"
    for i,q in enumerate(query_history[-5:],1):
        message += f"{i}. {q['answer']}\n\n"
    return "https://wa.me/?text=" + urllib.parse.quote(message)

def facebook_share():
    if not query_history:
        return "No queries available."
    message = "SQL Queries:\n\n"
    for q in query_history[-3:]:
        message += f"{q['answer']}\n"
    return "https://www.facebook.com/sharer/sharer.php?u=" + urllib.parse.quote(message)

def export_pdf():
    if not query_history:
        return None
    filename = f"SQL_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph("SQL Query Report", styles["Heading1"]))
    story.append(Spacer(1,0.3*inch))
    for i,q in enumerate(query_history,1):
        story.append(Paragraph(f"<b>Query {i}</b>", styles["Heading2"]))
        story.append(Paragraph(q["answer"], styles["Normal"]))
        story.append(Spacer(1,0.3*inch))
    doc.build(story)
    return filename

def export_txt():
    if not query_history:
        return None
    filename = f"SQL_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(filename,"w") as f:
        for i,q in enumerate(query_history,1):
            f.write(f"{i}. {q['answer']}\n\n")
    return filename

custom_css = """
body, .gradio-container {
    background: linear-gradient(135deg, #0b1120, #1e293b) !important;
}
h1, h2, h3, h4, p, label {
    color: #ffffff !important;
}
button {
    background: linear-gradient(90deg, #3b82f6, #2563eb) !important;
    color: #ffffff !important;
    border-radius: 10px !important;
    height: 45px !important;
}
"""

with gr.Blocks(theme=gr.themes.Base(), css=custom_css) as demo:

    gr.Markdown("# 🔎 SQL Query Generator")
    gr.Markdown("### Natural Language → SQLite SQL")
    gr.Markdown("Convert plain English requests into safe, production-ready SQL queries!")

    with gr.Row():
        with gr.Column(scale=3):
            sql_output = gr.HTML(styled_box(), label="Query Conversion")
            user_input = gr.Textbox(label="Natural Language Request")
            generate_btn = gr.Button("Generate SQL")

        with gr.Column(scale=1):
            gr.Markdown("## Controls")
            clear_btn = gr.Button("Clear History")

            gr.Markdown("## Share")
            wa_btn = gr.Button("WhatsApp")
            fb_btn = gr.Button("Facebook")
            share_box = gr.Textbox(label="Share Link")

            gr.Markdown("---")

            gr.Markdown("## 📊 Schema Info")
            gr.Markdown("""
*Tables:*
•⁠  ⁠users
•⁠  ⁠orders
•⁠  ⁠products
•⁠  ⁠transactions
---
### Supported Requests:
•⁠  ⁠User queries (last month, last year, signup date)
•⁠  ⁠Order lookups
•⁠  ⁠Product searches
•⁠  ⁠Transactions greater than X amount
•⁠  ⁠Last week / last month filters
•⁠  ⁠Amount greater than / more than queries
""")

            gr.Markdown("---")

            gr.Markdown("## Export")
            pdf_btn = gr.Button("Download PDF")
            txt_btn = gr.Button("Download TXT")
            pdf_file = gr.File(label="PDF File")
            txt_file = gr.File(label="TXT File")

    generate_btn.click(generate_sql, user_input, sql_output)
    clear_btn.click(clear_history, outputs=sql_output)
    wa_btn.click(whatsapp_share, outputs=share_box)
    fb_btn.click(facebook_share, outputs=share_box)
    pdf_btn.click(export_pdf, outputs=pdf_file)
    txt_btn.click(export_txt, outputs=txt_file)

demo.launch(share=True)